import asyncio
from datetime import datetime
import json
import logging
import urllib.error
import urllib.request

from app.core.config import settings
from app.schemas.llm_tools import GROQ_TOOLS

logger = logging.getLogger(__name__)

GROQ_COMPLETIONS_URL = "https://api.groq.com/openai/v1/chat/completions"


def _build_system_instruction() -> str:
    today_str = datetime.now().strftime("%Y-%m-%d")
    return (
        f"คุณคือผู้ช่วยจัดการข้อมูลการสมัครงานอัจฉริยะ 'JobTrack' ประจำ LINE Bot\n"
        f"วันนี้คือวันที่: {today_str}\n\n"
        f"หน้าที่ของคุณคือเข้าใจความต้องการของผู้ใช้และเลือกเรียกใช้ Tool ที่ถูกต้อง:\n"
        f"1. เมื่อผู้ใช้บอกว่าสมัครงาน ยื่นใบสมัคร หรือเพิ่มงานใหม่ ให้เรียก Tool `create_job_application`\n"
        f"   - ต้องมีชื่อบริษัท (company) และตำแหน่ง (position) เสมอ\n"
        f"   - ถ้าขาดชื่อตำแหน่ง หรือชื่อบริษัท ให้ตอบเป็นข้อความถามผู้ใช้กลับไปอย่างสุภาพ อย่าเดาเอง\n"
        f"   - ถ้าผู้ใช้ระบุว่า 'วันนี้' หรือ 'เมื่อวาน' ให้คำนวณเป็นวันที่ YYYY-MM-DD\n"
        f"2. เมื่อผู้ใช้ต้องการดูรายการงาน ค้นหางาน หรือถามว่าสมัครงานอะไรไปบ้าง (เช่น 'ดูรายการสมัครงานทั้งหมด', 'สมัครอะไรไปบ้าง', 'ขอดูงาน Shopee') ให้เรียก Tool `query_job_applications`\n"
        f"3. เมื่อผู้ใช้ต้องการดูสรุปสถิติ ภาพรวม ตัวเลข หรือ Dashboard (เช่น 'สรุปสถิติ', 'สรุปข้อมูลการสมัครงาน', 'รายงานภาพรวม', 'สถิติการสมัคร') ให้เรียก Tool `get_application_summary`\n"
        f"4. เมื่อผู้ใช้ต้องการอัปเดตสถานะ เช่น 'KBank นัดสัมภาษณ์แล้ว', 'ผ่านสัมภาษณ์ SCB แล้ว' ให้เรียก Tool `update_job_application`\n"
        f"5. เมื่อผู้ใช้ต้องการลบงาน เช่น 'ขอลบงาน Agoda' ให้เรียก Tool `delete_job_application`\n"
        f"6. เมื่อผู้ใช้ต้องการดาวน์โหลด หรือ Export ข้อมูลเป็นไฟล์ Excel (XLSX) ให้เรียก Tool `export_applications`\n"
        f"7. ถ้าผู้ใช้พูดคุยทั่วไป ทักทาย หรือถามการใช้งาน ให้ตอบกลับด้วยภาษาไทยที่เป็นมิตร สุภาพ มี emoji เหมาะสม โดยไม่ต้องเรียก Tool\n"
        f"ห้ามกุข้อมูลขึ้นมาเองโดยเด็ดขาด"
    )


def _call_groq_api_sync(user_message: str, api_key: str, model: str) -> dict:
    if not api_key:
        logger.warning("GROQ_API_KEY is not configured.")
        return {
            "type": "text",
            "text": "ขออภัยครับ ขณะนี้ยังไม่ได้ตั้งค่า GROQ_API_KEY ในระบบ",
        }

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": _build_system_instruction()},
            {"role": "user", "content": user_message},
        ],
        "tools": GROQ_TOOLS,
        "tool_choice": "auto",
        "temperature": 0.1,
    }

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        GROQ_COMPLETIONS_URL,
        data=data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
            "User-Agent": "JobTrack/1.0",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=15) as res:
            response_json = json.loads(res.read().decode("utf-8"))
            choices = response_json.get("choices", [])
            if not choices:
                return {
                    "type": "text",
                    "text": "ขออภัยครับ ไม่สามารถรับคำตอบจากโมเดลได้ในขณะนี้",
                }

            message = choices[0].get("message", {})
            tool_calls = message.get("tool_calls")

            # Check if model executed a tool call
            if tool_calls and len(tool_calls) > 0:
                tool_call = tool_calls[0]
                function_info = tool_call.get("function", {})
                func_name = function_info.get("name")
                raw_args = function_info.get("arguments", "{}")

                if isinstance(raw_args, str):
                    try:
                        args = json.loads(raw_args)
                    except json.JSONDecodeError:
                        args = {}
                else:
                    args = raw_args

                # Clean up null/empty values generated by the model
                if isinstance(args, dict):
                    args = {k: v for k, v in args.items() if v is not None and v != ""}

                return {
                    "type": "function_call",
                    "name": func_name,
                    "args": args,
                }

            # Regular conversational text response
            content = message.get("content") or ""
            return {
                "type": "text",
                "text": content,
            }

    except urllib.error.HTTPError as e:
        err_msg = e.read().decode("utf-8", errors="replace")
        logger.error(f"Groq API HTTP Error {e.code}: {err_msg}")
        return {
            "type": "text",
            "text": "ขออภัยครับ เกิดข้อผิดพลาดในการเชื่อมต่อกับ Groq API ชั่วคราว",
        }
    except Exception as e:
        logger.error(f"Unexpected error calling Groq API: {e}")
        return {
            "type": "text",
            "text": "ขออภัยครับ เกิดข้อผิดพลาดในการประมวลผลข้อความ",
        }


async def parse_intent_with_groq(user_message: str) -> dict:
    """Async wrapper to parse intent using Groq API in a background thread."""
    return await asyncio.to_thread(
        _call_groq_api_sync,
        user_message,
        settings.groq_api_key,
        settings.groq_model,
    )
